require("plugins_config.telescope")
require("plugins_config.lsp")
require("plugins_config.themery")
require("plugins_config.treesitter")
require("plugins_config.conform")
require("plugins_config.themery")
require("plugins_config.nvim_tree")
