local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader><leader>", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fj", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fa", function()
	builtin.find_files({ ignore = true, hidden = true })
end, { desc = "Telescope find files with hidden and gitignored" })
